In [1]:
#Importing the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# import seaborn as sns

In [3]:
#Importing the dataset
data = pd.read_csv("C:/Users/HI/OneDrive/Documents/linear regression.csv")
data.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   2210
1   44.5   39.3       45.1   1040
2   17.2   45.9       69.3    930
3  151.5   41.3       58.5   1850
4  180.8   10.8       58.4   1290

In [4]:
X = data['TV'].values.reshape(-1,1)
y = data['sales'].values.reshape(-1,1)

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [6]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(X_train, y_train)

LinearRegression()

In [7]:
y_pred = reg.predict(X_test)
#y_pred

In [8]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.6714477229302764

In [9]:
output = reg.predict([[300.06]])
output

array([[2116.45849373]])

In [10]:
#Intercept
reg.intercept_

array([723.94598308])

In [11]:
reg.coef_

array([[4.64078021]])